logging:
  config: classpath:log4j2-spring.xml
  file:
    name: ./logs/zmq_pub_sub.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${pid} ---  [%t] %-40.40c{1.} : %X{correlation_id} : %m%n%xwEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5p ${pid} ---  [%t] %-40.40c{1.} : %X{correlation_id} : %m%n%xwEx"

server:
  port: 8088

spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  application:
    name: zmqPubSub

# Enable swagger generation
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

output-directory: messages
# When true, the output directory will be cleared and recreated on application startup
output-directory-clear-on-startup: true

# The root directory for file operations (publishing, Lua scripts, etc.)
workspace-root: .
