### Create a periodic publisher
POST http://localhost:8088/register-periodic-publisher
Content-Type: application/json

{
  "name": "periodic publisher 1",
  "address": "tcp://*:5556",
  "topic": "heartbeat",
  "message": "{\"name\":\"MyApp\",\"isMain\":true}",
  "period": 2000
}

### Register a subscriber for the above publisher
POST http://localhost:8088/register-subscriber
Content-Type: application/json

{
  "name": "Subscriber 1",
  "address": "tcp://localhost:5556"
}

### Update the message being published periodically
POST http://localhost:8088/update-periodic-message
Content-Type: application/json

{
  "name": "periodic publisher 1",
  "message": "{\"name\":\"MyApp\",\"isMain\":false}"
}

### Post a message to the periodic publisher
POST http://localhost:8088/publish
Content-Type: application/json

{
  "publisherName": "periodic publisher 1",
  "topic": "MESSAGES",
  "message": "We can publish to a publisher that is publishing periodically"
}

### Register a publisher
POST http://localhost:8088/register-publisher
Content-Type: application/json

{
  "name": "One-shot publisher",
  "address": "tcp://*:5557"
}

### Register a subscriber for the above publisher
POST http://localhost:8088/register-subscriber
Content-Type: application/json

{
  "name": "Subscriber 2",
  "address": "tcp://localhost:5557"
}

### Register a binary subscriber
POST http://localhost:8088/register-subscriber
Content-Type: application/json

{
  "name": "Binary Subscriber",
  "address": "tcp://localhost:5557",
  "binary": true
}

### Post a message to the one-shot publisher
POST http://localhost:8088/publish
Content-Type: application/json

{
  "publisherName": "One-shot publisher",
  "topic": "system",
  "message": "This is not a JSON message!"
}

### Register a publisher for file publishing (single file)
POST http://localhost:8088/register-publisher
Content-Type: application/json

{
  "name": "Files Publisher 1",
  "address": "tcp://*:5558"
}

### Publish a single file
POST http://localhost:8088/publish-files
Content-Type: application/json

{
  "file": "E:/projects2025/zmq-play/LICENSE",
  "topic": "legal",
  "publisherName": "Files Publisher 1",
  "binary": false
}

### Register a publisher for file publishing (directory)
POST http://localhost:8088/register-publisher
Content-Type: application/json

{
  "name": "Files Publisher 2",
  "address": "tcp://*:5559"
}

### Publish all files in a directory
POST http://localhost:8088/publish-files
Content-Type: application/json

{
  "directory": "E:/projects2025/zmq-play/messages/subscriber_1",
  "topic": "archive",
  "publisherName": "Files Publisher 2",
  "delay": 1000,
  "binary": true
}

### Register a monitored subscriber
POST http://localhost:8088/register-monitored-subscriber
Content-Type: application/json

{
  "name": "monitored subscriber",
  "address": "tcp://localhost:5556",
  "topic": "heartbeat",
  "watchdogPeriod": 1000,
  "failureThreshold": 2,
  "binary": false
}

### Deregister a publisher
POST http://localhost:8088/deregister-publisher
Content-Type: application/json

{
  "name": "periodic publisher 1"
}

### List all publishers
GET http://localhost:8088/list-publishers